language: swift
osx_image: xcode10.2
xcode_destination: platform=macOS
xcode_workspace: Fenris.xcworkspace
xcode_scheme: "Fenris macOS"
script:
  - make build
  - set -o pipefail && make test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Fenris'
