language: swift
osx_image: xcode10.2
xcode_destination: platform=macOS
xcode_workspace: Fenris.xcworkspace
xcode_scheme: "Fenris macOS"
env:
  global:
  - secure: efsu+3jQaaN8B8z7FqDd0mzxMmJ+irf2RjgsOVJVr++uxJmd/u66Fcj91LYWXaSfM7b5KL094Zqr1YZOKbNs1AVcaWj5LMJuK9HOl0TjYhhqD/3UJ7htRxZMScXM5NQI0+P4iTbxjTX6vku7sDxsRY7XOOq1+GCkJBWKBLH5359euo88WHs/vJYZCHyfi0MZjnpkY54zfTXkunjocvzhWhd+pMUo6gleCDOGfVAFb2Sliwbh4uIIKnh55/78xiRbewE0NEWHyPE70wZ+G2v82L8Vp70GDpsBTwsZ8WLzveL9FXnbXwubMcTyQ15nQWftguCCDdBzLOL62tNjyzjip6j1gZ2iDQpynqteLTz9IyrFKWzR24RbRcu7X+PLcnV4Ra/FGTEqSDQl8ZJhOIWB6m2+ailheKYRemxFjiUMV6vj+xPZRN2trZygS451uek9OEAdGPbhBxkKTWwRoM8EnILpActCiHeqlJzT63BxOkO9LXjD9VX9V9qjx4E0kQJ+DI7jEV4tesosGYRFqlXUR20glfRWiZGQiFN5DiWKKJRUX5Cr//wGQoX8bdjT+WazKbP5mzkB6QDmUyPsyD1UnDuN+tW+iFIHGZxeiW1gEievUGTaz4MwBV3wIQblEx8TkOHXisHJZfz22KTLTHxWcHqYYR7XFq6qlbBn5K8KN5M=
  - secure: hpTvnJbDFKHkNB37eVoHw/V7Cjubv0EAW+M/omqumJ0tKQNhxTtTVDf76Ss+kwH7+mPs3dRb2LCbzU4L4T2soPAHZiQ9lUS4RGKoqKRLxmPZAvlKVAq4z6PJYKAPitcXUoLyiWIH9tYAxjuXj3/OpPT4923uU1ejlV27t1LDih11zlk88RZ/pZNMLINtNEPC+0e9LstzsX0tAs+li2/nBD/VMGc8VmTk3dwyy15XXgfNlOIek6abW8gBNvvTlMPF0D1OsVM+xW4OjEnCjD9gsPuuQqZUG8NFPxLnvOqkYa83ZCNGcBgnL16Riea12ho5LAcXZdFkWXu3as5YSRDPXtjAMQSsAl7OIIUMPzCCaWarQztaqPtUYjffpd4fTxnbGjeZHlgdvLlMWKQhUR3ftmCv9SCcoVPnwP086Qk8ByM5unLVmED2sedvechGeh0UrQYOc21zdPbQkJU/eesktLGder0gIJaQmeo/+qe4yqu01qwaNmMUjUg243WUJ45Jgw8u/DguxdII1rXzNyZlwrygDqIHPnXpcNDmkuiZ0MNPCVBhsvmTFFzLTodcHyxSsDLg+7h4VhJPb5Sjcpwxp8FJeC8iL6HXd1tKgbenXFlIoR2XaqY7iGEvZ/tGvNL/Q4ybPle9W8a1FM18vTsVsUT2FQky0TMEd6j+Znkb/pw=
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
script:
- xcodebuild test -workspace "Fenris.xcworkspace" -scheme "Fenris macOS" -destination "platform=macOS,arch=x86_64" OBJROOT="$(PWD)/build" -sdk "macosx10.14"
after_script:
- ./scripts/remove-key.sh